version: '3.9'

services:

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
      - ./mongo-init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    networks:
      - students-network
  mongo-express:
    image: mongo-express:latest
    container_name: mongoui
    ports:
      - "8088:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    networks:
      - students-network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    networks:
      - students-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - students-network

  logstash:
    image: logstash:7.17.0
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./logs/application.log:/app/logs/application.log
    ports:
      - "5044:5044"
    networks:
      - students-network
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:7.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
    ports:
      - "9200:9200"
    networks:
      - students-network
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
      - es-data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:7.17.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - students-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - students-network

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - students-network
    depends_on:
      - prometheus

  domain-service:
    build:
      context: ./domain
      dockerfile: Dockerfile
    container_name: domain-service
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - students-network

  gateway-service:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - "8081:8081"
    depends_on:
      - domain-service
    environment:
      - ./logs/application.log:/app/logs/application.log
    networks:
      - students-network

networks:
  students-network:

volumes:
  mongo-data:
  logs:
  es-data:
    driver: local