spring:
  rabbitmq:
    host: rabbitmq
    virtual-host: vhost
    username: guest
    password: guest
  application:
    name: "domain"
  data:
    mongodb:
      uri: "mongodb://mongo:27017/adminka"