spring:
  application:
    name: "gateway"
  data:
    redis:
      port: 6379
      host: redis

logging:
  file:
    name: /Users/irvanev/development/Adminka/logs/application.log
  level:
    root: INFO
    org.springframework: DEBUG
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      all: true

server:
  port: 8081
