spring:
  application:
    name: "gateway"
  data:
    redis:
      port: 6379
      host: redis

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.cache: DEBUG
  appender:
    console:
      enabled: true
    logstash:
      enabled: true
      destination: logstash:5044
  logstash:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      all: true

server:
  port: 8081
